apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloakcontroller-deployment-role
rules:
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keycloak-quarkus-operator
    app.kubernetes.io/version: 0.0.6-SNAPSHOT
  name: keycloak-quarkus-operator-deployment-controller
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: keycloakcontroller-deployment-role
subjects:
  - kind: ServiceAccount
    name: keycloak-quarkus-operator
